language: python
cache: pip

matrix:
    fast_finish: true
    include:
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=2.2 }

      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=2.2 }

      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=2.2 }

install:
    - pip install tox tox-venv tox-travis

script:
    - tox

notifications:
    email: false
